name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - name: "random"
      run: echo $MY_NAME "From github actions" 
    env:
      MY_NAME: "Seeni"
